apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: inventory
data:
  espresso-shot: "10000"
  milk: "1000"
  milk-foam: "60000"
  hot-water: "99999999"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
  namespace: inventory
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: inventory-service
      environment: development
  template:
    metadata:
      labels:
        app: inventory-service
        environment: development
    spec:
      containers:
      - name: inventory-service
        image: sanketpatharkar/inventory-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: espresso-shot
          valueFrom:
            configMapKeyRef:
              name: inventory-service-config
              key: espresso-shot
        - name: milk
          valueFrom:
            configMapKeyRef:
              name: inventory-service-config
              key: milk
        - name: milk-foam
          valueFrom:
            configMapKeyRef:
              name: inventory-service-config
              key: milk-foam
        - name: hot-water
          valueFrom:
            configMapKeyRef:
              name: inventory-service-config
              key: hot-water
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory
  labels:
    app: inventory-service
    environment: development
spec:
  type: LoadBalancer  
  selector:
    app: inventory-service
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
