apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order
data:
  INVENTORY_URL: "http://inventory-service.inventory"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: order
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order-service
      environment: development
  template:
    metadata:
      labels:
        app: order-service
        environment: development
    spec:
      containers:
      - name: order-service
        image: sanketpatharkar/order-service:latest
        imagePullPolicy: Always
        env:
        - name: INVENTORY_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: INVENTORY_URL
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order
  labels:
    app: order-service
    environment: development
spec:
  type: LoadBalancer  
  selector:
    app: order-service
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
